stages:
- test
- deploy

before_script:
- apt-get update
- apt-get install redis-server -y
- redis-server --daemonize yes
- python -V
- pip install tox

test-py36-dj22:
  image: python:3.6-buster
  script:  
  - tox -e py36-django22

test-py37-dj22:
  image: python:3.7-buster
  script:  
  - tox -e py37-django22

test-py38-dj22:
  image: python:3.8-buster
  script:  
  - tox -e py38-django22

test-py36-dj30:
  image: python:3.6-buster
  script:  
  - tox -e py36-django30

test-py37-dj30:
  image: python:3.7-buster
  script:  
  - tox -e py37-django30

test-py38-dj30:
  image: python:3.8-buster
  script:  
  - tox -e py38-django30

test-linter:
  image: python:3.8-buster
  script:  
  - tox -e linter

deploy-pypi:
  stage: deploy
  image: python:3.7-buster

  before_script:
    - pip install twine

  script:
    - python setup.py sdist
    - twine upload dist/*

  only:
    - tags
