stages:
- checks
- test
- deploy

.tox_setup:
  before_script:
    - apt-get update
    - apt-get install redis-server -y
    - redis-server --daemonize yes
    - python -V
    - pip install tox

pre-commit:
  stage: checks
  image: python:3.10-bullseye
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files

# pylint:
#   stage: checks
#   extends: .tox_setup
#   image: python:3.10-bullseye
#   script:
#     - tox -e pylint
#   allow_failure: True

test-py38:
  extends: .tox_setup
  image: python:3.8-bullseye
  script:
    - tox -e py38-$DJANGO_VERSION
    - bash <(curl -s https://codecov.io/bash)
  parallel:
    matrix:
      - DJANGO_VERSION: [django32, django40, django41, django42]

test-py39:
  extends: .tox_setup
  image: python:3.9-bullseye
  script:
    - tox -e py39-$DJANGO_VERSION
    - bash <(curl -s https://codecov.io/bash)
  parallel:
    matrix:
      - DJANGO_VERSION: [django32, django40, django41, django42]

test-py310:
  extends: .tox_setup
  image: python:3.10-bullseye
  script:
    - tox -e py310-$DJANGO_VERSION
    - bash <(curl -s https://codecov.io/bash)
  parallel:
    matrix:
      - DJANGO_VERSION: [django32, django40, django41, django42]

test-py311:
  extends: .tox_setup
  image: python:3.11-bullseye
  script:
    - tox -e py311-$DJANGO_VERSION
    - bash <(curl -s https://codecov.io/bash)
  parallel:
    matrix:
      - DJANGO_VERSION: [django40, django41, django42]

test-docs:
  stage: test
  image: python:3.10-bullseye
  before_script:
  - pip install tox
  script:
    - tox -e docs

deploy-pypi:
  stage: deploy
  image: python:3.10-bullseye

  before_script:
    - pip install build wheel twine

  script:
    - python -m build
    - twine upload dist/*

  only:
    - tags
